version: "3.8"

services:
  backend:
    build: ./backend
    container_name: midi-backend
    restart: unless-stopped
    volumes:
      - midi-sessions:/tmp/midi_sessions
    environment:
      - FLASK_ENV=production
      - LLM_API_BASE=${LLM_API_BASE:-http://host.containers.internal:4000}
      - LLM_API_KEY=${LLM_API_KEY:-sk-placeholder}
    extra_hosts:
      - "host.containers.internal:host-gateway"

  frontend:
    build: ./frontend
    container_name: midi-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  midi-sessions:
